---
# This file is a template, and might need editing before it works on your project.

# Official language image. Look for the different tagged releases at:
# image: "python:2.7"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service

# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# variables:
#   POSTGRES_DB: database_name

# Cache packages in between builds
cache:
  paths:
    - vendor/python

# This is a basic example for a packages or script which doesn't use
# services such as redis or postgres
before_script:
  - docker run prosi3d:latest

build_image:
  script:
    - docker build -t prosi3d .
    - docker run prosi3d

.test_script: &test_script
  script:
    - tox
  # OR if you don't use tox:
  # - pytest

tests:
  image: "prosi3d:latest"
  <<: *test_script

docs:
  script:
    - tox -e docs

# This deploy job uses a simple deploy flow to Heroku, other providers, e.g. AWS Elastic Beanstalk
# are supported too: https://github.com/travis-ci/dpl
#deploy:
#  type: deploy
#  environment: production
#  script:
#    - python setup.py
#    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
