name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - keras
  - numpy
  - matplotlib
  - h5py
  - sphinx
  - autopep8
  - pytest
  - tox
  - setuptools
  - setuptools_scm
  - wheel
